### ISSUE TITLE
OOM Error

### ISSUE THREAD

**Issue by mubashirbashir** [facebook/shimmer-android#102]
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 12 byte allocation with 0 free bytes and -2MB until OOM
       at java.lang.Float.valueOf(Float.java:441)
       at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.getAnimatedValue(PropertyValuesHolder.java:1331)
       at android.animation.ValueAnimator.getAnimatedValue(ValueAnimator.java:782)
       at com.facebook.shimmer.ShimmerFrameLayout$2.onAnimationUpdate(ShimmerFrameLayout.java)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1346)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1258)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1306)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:925)
       at android.view.Choreographer.doCallbacks(Choreographer.java:702)
       at android.view.Choreographer.doFrame(Choreographer.java:635)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by xiphirx** [comment]
Your app is using too much memory to the point that it wasn't able to allocate a `Float`. I would investigate your app's memory usage.
