### ISSUE TITLE
Unable to create layer for ShimmerFrameLayout

### ISSUE THREAD

**Issue by ikocijan** [facebook/shimmer-android#75]
On LG  G3 (LG-D855) there is a strange exception related to ShimmerFrameLayout. Here is a full stacktrace:

```
Fatal Exception: java.lang.IllegalStateException: Unable to create layer for ShimmerFrameLayout
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:323)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

I know, it's a 5 years old phone, however, it supports Android 6.0 so it would be good to check why this is happening.

**Comment by xiphirx** [comment]
This usually means you're trying to apply a shimmer effect to a view that is too large for the gpu (typically larger than 4096x4096). A common cause is trying to apply a shimmer to a scrolling view.

**Comment by rrifafauzikomara** [comment]
@xiphirx I have the same problem. So how to fix it?

**Comment by pavan555** [comment]
how to solve this issue

**Comment by vijaydream11** [comment]
is there any fix ?

**Comment by irfanirawansukirman** [comment]
@xiphirx

**Comment by WendyYanto** [comment]
Hi , does it mean Shimmering should not be added in a ScrollView ? or is there any alternatives ?
